baseURL = 'https://blog.oyyko.com'
DefaultContentLanguage = "en"
title = "Oyyko's Blog"
theme = "diary"
publishDir = "docs"
enableGitInfo = true

[params]
enableUtterances = true
Subtitle = "Being towards death"
favicon = "https://avatars.githubusercontent.com/u/66729335?v=4"

[taxonomies]
   tag = "tags"

[params.utterances]
repo="Oyyko/utteranc-comments"
term="pathname"
theme="github-light"

[[menu.main]]
url = "/about"
name = "About"
weight = 3

[[menu.main]]
url = "/tags"
name = "Tags"
weight = 2

[[menu.main]]
url = "/posts"
name = "Archive"
weight = 1

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "emacs"
    tabWidth = 4