baseURL = 'https://blog.oyyko.com'
DefaultContentLanguage = "en"
title = "Oyyko's Blog"
theme = "diary"
publishDir = "docs"

[params]
enableUtterances = true
Subtitle = "Are you winning son?"

[taxonomies]
   tag = "tags"
   category = "categories"

[params.utterances]
repo="Oyyko/utteranc-comments"
term="pathname"
theme="github-light"


[[menu.main]]
url = "/categories/Study"
name = ":Study"
weight = 6

[[menu.main]]
url = "/categories/Coding"
name = ":Coding"
weight = 5

[[menu.main]]
url = "/categories/life"
name = ":Life"
weight = 4

[[menu.main]]
url = "/about"
name = "About"
weight = 3

[[menu.main]]
url = "/tags"
name = "Tags"
weight = 2

[[menu.main]]
url = "/posts"
name = "Archive"
weight = 1